#!/usr/bin/env python3
"""Idempotent identifier codemod for the Vaelis/Hermes -> Plobi rename (R-038).

Dry-run by default. Layers select which token families move, so each rename
slice stays independently reviewable and revertible:

  s2   our own identifiers only   (vaelis / Vaelis / VAELIS)
  s3   upstream layer only        (hermes / Hermes / HERMES)
  s4   outward-facing layer       (both tokens, --prefix scoped to build config,
                                   locales and notify copy)
  s5   documentation tree         (both tokens, Docs/ only, history-protected)
  all  s2 + s3

Why a script and not sed: a blanket substitution rewrites upstream attribution
URLs, contributor e-mail domains, license files and lockfile payloads, all of
which must survive verbatim (Docs/PLOBI-RENAME.md 2.4). Reserved spans are
lifted out of the text before substitution and put back afterwards, so the rules
never see them.

Lockfiles are excluded on purpose: uv.lock and package-lock.json are
regenerated by `uv lock` / `npm install` once the manifests change, not
text-patched.

Case is preserved by shape: hermes -> plobi, Hermes -> Plobi, HERMES -> PLOBI.

Usage:
  python scripts/rename_plobi.py --layer s2                  # dry-run report
  python scripts/rename_plobi.py --layer s2 --apply
  python scripts/rename_plobi.py --layer s2 --apply --list-changed
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

FAMILIES = {"vaelis": ("vaelis", "plobi"), "hermes": ("hermes", "plobi")}
LAYER_FAMILIES = {
    "s2": ["vaelis"],
    "s3": ["hermes"],
    "s4": ["vaelis", "hermes"],
    "s5": ["vaelis", "hermes"],
    "all": ["vaelis", "hermes"],
}

# Spans that must survive verbatim (legal attribution, mailmap, external URLs).
PROTECT = [
    r"https?://(?:www\.)?github\.com/NousResearch/[^\s\"'`)\]]*",
    r"https?://discord\.gg/NousResearch",
    r"[A-Za-z0-9._%+-]+@nousresearch\.com",
    r"https?://pypi\.org/project/[A-Za-z0-9._-]+",
    # Markdown links whose *label* names upstream: keep the whole link, since
    # the label refers to Nous Research's project. A label naming us is still
    # rewritten -- "[Vaelis Agent](https://github.com/NousResearch/hermes-agent)"
    # is our product name glued to an upstream URL, and the URL alone is
    # covered by the rule above.
    r"\[(?=[^\]\n]*(?i:hermes))[^\]\n]*\]\(\s*https?://github\.com/NousResearch/[^\)]*\)",
    # Real third-party model identifiers (Nous Hermes 2/3/4, openrouter/hermes3).
    # Renaming these makes the product address a model that does not exist.
    # The separator is at most one character on purpose: allowing arbitrary
    # whitespace once swallowed `${cfg.stateDir}/.hermes` in nix/nixosModules.nix
    # because a permission number happened to follow it on the same line.
    r"(?:nous[\s_-]+)?[Hh][Ee][Rr][Mm][Ee][Ss][\s_-]?\d[\w.:-]*",
]
PROTECT_RE = re.compile("|".join(f"(?:{p})" for p in PROTECT))

# Four word shapes, all case-insensitive, replacement mirrors the matched shape:
#   standalone / separator-adjacent   hermes_cli, .hermes, HERMES_HOME, hermes-agent
#   PascalCase compound start         HermesCLI, HermesServer
#   camelCase middle                  currentHermesSessionId
#   camelCase end                     startHermes()
# Deliberately NOT matched: a stem glued to a following lowercase word
# (hermesclaw, hermesagent — other people's repos and handles) or to a digit
# (hermes3 — covered above as a protected model id).
#
# The neighbour classes are scoped with (?-i:...) on purpose: under a global
# IGNORECASE, [A-Z] would also match lowercase letters and 'hermesclaw' would be
# swallowed by the PascalCase rule.
_SHAPES = (
    r"(?<![A-Za-z0-9]){src}(?![A-Za-z0-9])",
    r"(?<![A-Za-z0-9]){src}(?=(?-i:[A-Z]))",
    r"(?<=(?-i:[a-z0-9])){src}(?=(?-i:[A-Z]))",
    r"(?<=(?-i:[a-z0-9])){src}(?![A-Za-z0-9])",
)


def stem_pattern(src: str) -> re.Pattern:
    alts = "|".join(s.format(src=src) for s in _SHAPES)
    return re.compile(alts, re.IGNORECASE)

ROOTED = {name: stem_pattern(src) for name, (src, _dst) in FAMILIES.items()}


def loose_pattern(src: str) -> re.Pattern:
    """Any occurrence of the stem, for the post-apply residual audit."""
    return re.compile(src, re.IGNORECASE)


# Content rules that must run before the generic stem sweep, because their
# target is not a plain stem-for-stem substitution.
SPECIFIC = [
    # The repo-root launcher `./hermes` cannot become `./plobi`: S2 already made
    # `plobi/` the package directory. It lands on plobi.py, in the style of the
    # other root entry points (cli.py, run_agent.py).
    #
    # Must be anchored on BOTH sides. An unanchored `\./hermes\b` fired inside
    # longer paths: it ate `'../hermes'` (a TypeScript module import),
    # `.../hermes-gateway.service`, `C:/Users/.../hermes-snap-*.sh` and
    # `./hermes-agent.nix`, producing `plobi.py-agent.nix` and friends. So: no
    # path separator, dot (including ellipses) or word character in front, and
    # nothing that would make it part of a longer name after it.
    (re.compile(r"(?<![\w./])\./hermes\b(?![\w./-])"), "./plobi.py", "hermes"),
]

# Path rename exceptions, mirroring SPECIFIC.
PATH_OVERRIDES = {"hermes": "plobi.py"}

LEGAL_BASENAMES = {"LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING", "NOTICE"}
LOCK_BASENAMES = {"package-lock.json", "uv.lock", "bun.lockb", "pnpm-lock.yaml"}
SKIP_DIR_PARTS = {"node_modules", ".venv", "__pycache__", "dist", "build", ".git"}
# The codemod and its contract tests carry the old stems as *rule data*
# (FAMILIES, the preserve-list). Rewriting them would silently turn the tool
# into a no-op and delete the evidence that foreign identifiers survive.
SELF_EXCLUDE = {"scripts/rename_plobi.py", "tests/scripts/test_rename_plobi.py"}
SKIP_SUFFIXES = (".png", ".jpg", ".jpeg", ".gif", ".ico", ".icns", ".pdf",
                 ".woff", ".woff2", ".ttf", ".mp3", ".wav", ".zip", ".gz",
                 ".tar", ".pyc", ".so", ".dll", ".dylib", ".node", ".exe",
                 ".bundle", ".lock")


def _skipped(rel: str, extra_excludes: tuple[str, ...] = ()) -> bool:
    if rel in SELF_EXCLUDE or any(rel.startswith(e) for e in extra_excludes):
        return True
    parts = rel.split("/")
    if any(p in SKIP_DIR_PARTS or p.endswith(".egg-info") for p in parts[:-1]):
        return True
    leaf = parts[-1]
    if leaf in LEGAL_BASENAMES or leaf in LOCK_BASENAMES:
        return True
    if rel.endswith(SKIP_SUFFIXES):
        return True
    return False


def tracked_files(root: Path, extra_excludes: tuple[str, ...] = ()) -> list[str]:
    out = subprocess.run(["git", "ls-files", "-z"], cwd=root,
                         capture_output=True, check=True).stdout
    return [r for r in out.decode().split("\0") if r and not _skipped(r, extra_excludes)]


def _match_case(dst: str, sample: str) -> str:
    if sample.isupper():
        return dst.upper()
    if sample[:1].upper() == sample[0] and sample[1:].lower() == sample[1:]:
        return dst[:1].upper() + dst[1:]
    return dst


def rewrite_text(text: str, families: list[str]) -> tuple[str, dict[str, int]]:
    slots: list[str] = []

    def stash(m):
        slots.append(m.group(0))
        return f"\x00P{len(slots) - 1}\x00"

    body = PROTECT_RE.sub(stash, text)
    counts: dict[str, int] = {f: 0 for f in families}
    for pat, repl, fam in SPECIFIC:
        if fam not in counts:
            continue
        body, cnt = pat.subn(repl, body)
        counts[fam] += cnt
    for fam in families:
        _src, dst = FAMILIES[fam]
        body, cnt = ROOTED[fam].subn(lambda m, d=dst: _match_case(d, m.group(0)), body)
        counts[fam] += cnt
    if slots:
        body = re.sub(r"\x00P(\d+)\x00", lambda m: slots[int(m.group(1))], body)
    return body, counts


def rename_component(name: str, families: list[str]) -> str:
    if name in PATH_OVERRIDES:
        return PATH_OVERRIDES[name]
    for fam in families:
        _src, dst = FAMILIES[fam]
        name = ROOTED[fam].sub(lambda m, d=dst: _match_case(d, m.group(0)), name)
    return name


def plan_renames(rels: list[str], families: list[str]) -> list[tuple[str, str]]:
    out = []
    for rel in rels:
        target = "/".join(rename_component(p, families) for p in rel.split("/"))
        if target != rel:
            out.append((rel, target))
    return out


def apply_renames(root: Path, pairs: list[tuple[str, str]]) -> int:
    # Fail before moving anything if two sources want one destination, or a
    # destination is already occupied -- a half-applied rename tree is much
    # harder to read than a refused one.
    seen: dict[str, str] = {}
    for src, dst in pairs:
        if dst in seen:
            sys.exit(f"rename collision: {src} and {seen[dst]} both target {dst}")
        seen[dst] = src
        if (root / dst).exists():
            sys.exit(f"rename collision: {dst} already exists (source {src})")

    moved = 0
    # Longest source path first: files inside a renamed directory move before
    # the directory itself would need to exist.
    for src, dst in sorted(pairs, key=lambda p: -p[0].count("/")):
        dest = root / dst
        dest.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["git", "mv", "-f", src, dst], cwd=root, check=True,
                       capture_output=True)
        moved += 1
    # git mv leaves emptied legacy directories behind; prune them.
    for d in sorted({p for src, _ in pairs for p in Path(src).parents},
                    key=lambda p: -len(p.parts)):
        dp = root / d
        if d != Path(".") and dp.is_dir():
            try:
                dp.rmdir()
            except OSError:
                pass
    return moved


def residual_report(root: Path, families: list[str], limit: int,
                    exclude: tuple[str, ...] = ()) -> int:
    """List surviving stems. Used after --apply to prove the sweep is complete
    and that every leftover is a deliberate exclusion (external name, legal
    text, protected model id), not a missed word shape."""
    rows = []
    for rel in tracked_files(root, exclude):
        p = root / rel
        try:
            raw = p.read_bytes()
        except OSError:
            continue
        if b"\x00" in raw[:8000]:
            continue
        for ln, line in enumerate(raw.decode("utf-8").splitlines(), 1):
            for fam in families:
                for m in loose_pattern(FAMILIES[fam][0]).finditer(line):
                    rows.append((fam, rel, ln, line.strip()[:120]))
    print(f"residual stems: {len(rows)}")
    for fam, rel, ln, snippet in rows[:limit]:
        print(f"  [{fam}] {rel}:{ln}: {snippet}")
    if len(rows) > limit:
        print(f"  ... {len(rows) - limit} more")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--layer", choices=sorted(LAYER_FAMILIES), default="s2")
    ap.add_argument("--root", default=str(REPO),
                    help="tree to sweep (pass the Docs/ checkout for --layer s5)")
    ap.add_argument("--prefix", action="append", default=[],
                    help="restrict to paths starting with these globs")
    ap.add_argument("--exclude", action="append", default=[],
                    help="skip paths starting with these prefixes (history "
                         "documents in layer s5 must not be rewritten)")
    ap.add_argument("--no-rename", action="store_true",
                    help="rewrite contents only, leave paths alone")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--verify", action="store_true",
                    help="list surviving stems instead of planning a rewrite")
    ap.add_argument("--limit", type=int, default=40, help="residual rows to print")
    ap.add_argument("--list-changed", action="store_true")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    families = LAYER_FAMILIES[args.layer]

    if args.verify:
        return residual_report(root, families, args.limit, tuple(args.exclude))

    all_rels = tracked_files(root, tuple(args.exclude))
    candidates = [r for r in all_rels
                  if not args.prefix or any(r.startswith(p) for p in args.prefix)]

    changed: list[str] = []
    per_family = {f: 0 for f in families}
    binary_skipped = 0

    for rel in candidates:
        p = root / rel
        try:
            raw = p.read_bytes()
        except OSError:
            continue
        if b"\x00" in raw[:8000]:
            binary_skipped += 1
            continue
        text = raw.decode("utf-8")
        new_text, counts = rewrite_text(text, families)
        if sum(counts.values()):
            for fam, cnt in counts.items():
                per_family[fam] += cnt
            changed.append(rel)
            if args.apply and new_text != text:
                p.write_text(new_text, encoding="utf-8", newline="")

    pairs = [] if args.no_rename else plan_renames(candidates, families)
    hits = sum(per_family.values())

    print(f"layer={args.layer}  families={'+'.join(families)}  root={root}")
    print(f"scanned={len(candidates)}  binary-skipped={binary_skipped}")
    for fam, cnt in per_family.items():
        print(f"  {fam:7s} hits={cnt}")
    print(f"total hits={hits}  files to change={len(changed)}")
    print(f"paths to rename={len(pairs)}")
    for src, dst in pairs[:15]:
        print(f"    {src}  ->  {dst}")
    if len(pairs) > 15:
        print(f"    ... {len(pairs) - 15} more")
    if args.list_changed:
        for rel in changed[:300]:
            print(f"  CHANGED {rel}")

    if not args.apply:
        print("dry-run: nothing written (pass --apply)")
        return 0
    moved = apply_renames(root, pairs) if pairs else 0
    print(f"applied: {len(changed)} files rewritten, {moved} paths renamed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
